Updates
seven48/vk_audios_bot pull request #1
Opened 2019-03-11 21:16 UTC by BehindLoader

2019-03-12 20:57 UTC, tmcgroul requested changes

2019-03-12 20:57 UTC, tmcgroul commented on src/routes/search.py
> +import src.models
ModuleNotFoundError: No module named 'src.models'

2019-03-13 22:42 UTC, ya7on reviewed
reminder for me

2019-03-13 22:42 UTC, BehindLoader commented on run.sh
> +>&2 echo "Migrations"
It's outdated. I'm using noSQL

2019-03-13 22:42 UTC, BehindLoader commented on src/models.py
> +mongo.connect('project1', host='0.0.0.0', port=27017)
Add customization

2019-03-16 10:15 UTC, tmcgroul requested changes

2019-03-16 10:15 UTC, tmcgroul commented on src/models.py
> +import mongoengine as mongo
requirements.txt must contain mongoengine

2019-03-16 10:15 UTC, tmcgroul commented on src/models.py
> +# pylint: disable=maybe-no-member
Not need

2019-03-16 10:15 UTC, tmcgroul commented on src/models.py
> +    user_id = mongo.IntField(unique=True)
Maybe specify some [field arguments](http://docs.mongoengine.org/guide/defining-documents.html#field-arguments)?

2019-03-16 10:15 UTC, tmcgroul commented on src/models.py
> +    _type = mongo.StringField()
Property `_type` not override built-in `type` func. So underscore for what?

2019-03-16 10:15 UTC, tmcgroul commented on src/utils/logger.py
> +    prefix = '[ {} ]'.format(datetime.now().strftime('%x %X'))
Look on [python string interpolation](https://www.python.org/dev/peps/pep-0498/). Interpolation looks cool.

2019-03-16 22:27 UTC, tmcgroul approved these changes

2019-03-16 22:28 UTC, merged