Master process
seven48/vk_audios_bot pull request #4
Opened 2019-03-16 22:57 UTC by BehindLoader

2019-03-22 20:23 UTC, tmcgroul requested changes

2019-03-22 20:23 UTC, tmcgroul commented on app.py
> +        src.bot.app.get_me()
`src.bot.app.get_me()` so many dots.
Maybe add import - `from src.bot import app as bot` or anything same.

2019-03-22 20:23 UTC, tmcgroul commented on src/models.py
> +                title=playlist.get("title"),
> Double quites near single quote

Please install [flake-plugin](https://github.com/zheller/flake8-quotes/)

2019-03-27 21:29 UTC, BehindLoader commented on app.py
> +        src.bot.app.get_me()
If i correctly understand, `import from` creates new copy of module. I do not need it. I need a link to it

2019-03-28 12:46 UTC, tmcgroul approved these changes

2019-03-28 12:47 UTC, merged